FROM python:3.6

WORKDIR /solidata_in_docker

COPY requirements.txt /solidata_in_docker/requirements.txt

RUN pip install -r requirements.txt

COPY . /solidata_in_docker

ENTRYPOINT ["gunicorn"]
CMD ["wsgi_prod_docker:app","--bind","0.0.0.0:4000"]
